spring:
  batch:
    job:
      names: ${job.name:NONE} #spring.batch.job.names 를 job.name 으로 치환
    jdbc:
      initialize-schema: always #초기 batch 스키마가 없으면 생성
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate #entity 를 보고 자동으로 데이터베이스  생성여부를 validate (생성x 검증만)
  datasource:
    url: jdbc:mysql://localhost:33060/point?useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: pass